# Travis CI script

language: c

os:
- linux

dist: trusty

sudo: required

addons:
  apt:
    packages:
    - libbsd-dev
    - libglib2.0-dev
    - libx11-dev
    - libkmod-dev

script: autoreconf -fi && ./configure && make distcheck

before_deploy:
- mkdir dist;
- export FILES=dist/*
- mv *.tar.gz dist
- cd dist
- sha1sum *.tar.gz > SHA1SUMS
- md5sum *.tar.gz > MD5SUMS
- cd -

deploy:
  provider: releases
  api_key:
    secure: uXUXUUAFTxfPsgoErM5biHHbNzdPq0DOmuOTUQZQ6op5oZeCRF0cgDsth3Ta492gL4j53swZcTsdMnKI1W/8ktCzMeKBi8IGbVXoK4SUJUlxf4l9vpOpkvTnuKECgbiz++XX6QdSaOHTrierf22xpY2MuDUL+tHpDgTdYABTa+ZQwCqiWG/KFZs+9dyGwvA9h9pwB0pxchJaHyVfBItW78EXVwnDBTY2aumFlYxN00WFWakJRYaAMSQ7TTFokXxXHEM259tzIzpB6KrFpGecgIA8GOo2tBkYhysuz8gsDjruQ3G7J8Iefu4vfJ2Q47Y/y2jt0vvOSFVOdeU1XWzQqrzMwRqUrsu/FFGgd0kwXMDVSm1XBBQF9TrrmCHT/zS9I6lq+dlZ0BiyoGFRibfrD3WUCGrLMeyi/WERXz7vPcTTZNZ4vUU4dHsfnJd9+XW4junNvSsR9Sc1UpnRDyz/sLnxhzosGnHeIPG6sRhgQTu3Iw03kE6hvVho1BR3E5YdZ3XeCai35ytrJqqVr1Nmw79QOvNNh1jzVlXxbCIlHUhFpfojqL/dTnoSzn63RGkl9g4+jX7uq6WB17nGPoSOwz29tcBHQGgbgzyooKkvy+IX11kd/LllTjfINHc/ke1GNcXDSqnsr5XD2zkNmtwYj04CooFGqcJbu5aSW5BDnsg=
  file: "${FILES}"
  skip_cleanup: true
  file_glob: true
  on:
    repo: bluca/Bumblebee
    branch: travis
    tags: true
